from typing import Any

async def connect(uri: str) -> WebSocketClientProtocol: ...

class WebSocketClientProtocol:
    async def send(self, message: str | bytes) -> None: ...
    async def recv(self) -> str | bytes: ...
    async def close(self) -> None: ...

